import React from "react";
import { createRoot } from "react-dom/client";

/**
 * Header
 *  - Logo
 *  - Nav Items
 * Body
 *  - Search
 *  - Restaurant Container
 *  - Restaurant Card
 * Footter
 *  - Copy
 *  - Links
 *  - Address
 *  - Contact
 */

const Header = () => {
  return (
    <div className="header">
      <div className="logo-container">
        <img
          className="logo"
          src="https://www.designmantic.com/logo-images/5807.png?company=Company%20Name&keyword=food&slogan=&verify=1"
        />
      </div>
      <div className="nav-items">
        <ul>
          <li>Home</li>
          <li>About Us</li>
          <li>Contact Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

const styleCard = {
  backgroundColor: "#f0f0f0",
};

const RestaurantCard = ({ resData }) => {
  const {
    restaurantLogoUrl,
    restaurantName,
    restaurantAddress,
    restaurantCuisineKeysList,
    reviewsRankDecimal,
    deliveryTimeInMinutes,
  } = resData;

  return (
    <div className="res-card" style={styleCard}>
      <img className="res-logo" alt="res-logo" src={restaurantLogoUrl} />
      <h3>{restaurantName}</h3>
      <h3>{restaurantAddress}</h3>
      <h4>{restaurantCuisineKeysList?.join(", ")}</h4>
      <h4>{reviewsRankDecimal} stars</h4>
      <h4>{deliveryTimeInMinutes} minuts</h4>
    </div>
  );
};

const resList = [
  {
    restaurantId: 46187,
    restaurantName: "בזאר המשקאות",
    localizationNames: {
      he: "בזאר המשקאות",
      en: "Bazar Ha Mashkaot",
    },
    restaurantAddress: "ניסים אלוני, 2 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46187.jpg",
    restaurantCuisineKeysList: ["alcoholic"],
    restaurantCuisineTypes: {},
    distanceFromUser: 442.29269201820176,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "07:00",
    closeTime: "23:45",
    deliveryTimeInMinutes: 30,
    numOfReviews: 5,
    reviewsRankDecimal: 3.8,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 25,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 25,
    minimumPriceForOrder: 199,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 100,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46187_20250910140709.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 2,
    businessTypeName: "GroceryStore",
    defaultDeliveryRuleType: "Future",
  },
  {
    restaurantId: 46055,
    restaurantName: "בוב בורגרס",
    localizationNames: {
      he: "בוב בורגרס",
      en: "Bob Burgers",
    },
    restaurantAddress: "רחוב שייקה אופיר, 3 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46055.jpg",
    restaurantCuisineKeysList: ["burgers"],
    restaurantCuisineTypes: {
      burgers: "המבורגר",
    },
    distanceFromUser: 334.6918827779206,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "11:00",
    closeTime: "22:30",
    deliveryTimeInMinutes: 35,
    numOfReviews: 7,
    reviewsRankDecimal: 4,
    discountPercent: 10,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        minimumPriceForDiscount: 0,
        discountType: "Percent",
        type: "DiscountCoupon",
        value: "10%",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 124,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "בעקבות מזג האוויר ייתכן ויהיו עיכובים בזמני המשלוח",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46055_20250826082221.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 21463,
    restaurantName: "טורקיז שווארמה",
    localizationNames: {
      he: "טורקיז שווארמה",
      en: "Turkiz shawarma",
    },
    restaurantAddress: "הרב שלום שבזי, 229 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/21463.jpeg",
    restaurantCuisineKeysList: ["meatGrill", "homeMade"],
    restaurantCuisineTypes: {
      meatGrill: "בשרים",
      homeMade: "אוכל ביתי",
    },
    distanceFromUser: 316.7722350477482,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "10:00",
    closeTime: "22:00",
    deliveryTimeInMinutes: 35,
    numOfReviews: 3220,
    reviewsRankDecimal: 4.2,
    discountPercent: 0,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 208,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "טורקיז שווארמה | שבזי 229 ראש העין",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_21463_20251205080659.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 33865,
    restaurantName: "פאפא ג'ונס ראש העין ",
    localizationNames: {
      he: "פאפא ג'ונס ראש העין ",
      en: "Papa Johns",
    },
    restaurantAddress: "העמל, 13 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/33865.jpeg",
    restaurantCuisineKeysList: ["pizza", "veganFood", "glutenFree"],
    restaurantCuisineTypes: {
      pizza: "פיצה",
      veganFood: "אוכל טבעוני",
      glutenFree: "ללא גלוטן",
    },
    distanceFromUser: 2585.061923543958,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "12:00",
    closeTime: "23:45",
    deliveryTimeInMinutes: 35,
    numOfReviews: 306,
    reviewsRankDecimal: 4.2,
    discountPercent: 20,
    isKosher: false,
    isVegan: true,
    isGlutenFree: true,
    isEnvironmentFriendly: false,
    deliveryFee: 16,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 16,
    minimumPriceForOrder: 69.9,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        minimumPriceForDiscount: 0,
        discountType: "Percent",
        type: "DiscountCoupon",
        value: "20%",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 42,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "רשת הפיצריות הבינלאומית",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_33865_20250721084756.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 40576,
    restaurantName: "דומו פיצה&פסטה ראש העין",
    localizationNames: {
      he: "דומו פיצה&פסטה ראש העין",
      en: "Domo Pizza",
    },
    restaurantAddress: "רחוב שייקה אופיר, 3 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/40576.jpg",
    restaurantCuisineKeysList: ["pizza", "salads", "pasta"],
    restaurantCuisineTypes: {
      pizza: "פיצה",
      salads: "סלטים",
      pasta: "פסטה",
    },
    distanceFromUser: 390.8198143639737,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "12:00",
    closeTime: "23:00",
    deliveryTimeInMinutes: 35,
    numOfReviews: 18,
    reviewsRankDecimal: 3.6,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 34,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_40576_20250811160132.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 40732,
    restaurantName: "ארי משקאות | אלכוהול",
    localizationNames: {
      he: "ארי משקאות | אלכוהול",
      en: "Ari Drinks",
    },
    restaurantAddress: "היצירה, 11 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/40732.jpeg",
    restaurantCuisineKeysList: ["alcoholic"],
    restaurantCuisineTypes: {
      alcoholic: "חנות אלכוהול",
    },
    distanceFromUser: 4416.061618030673,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "11:00",
    closeTime: "20:00",
    deliveryTimeInMinutes: 30,
    numOfReviews: 16,
    reviewsRankDecimal: 4,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 24,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 24,
    minimumPriceForOrder: 0,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 224,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement:
      "זמני האספקה להזמנות הם 2–5 ימי עסקים. המערכת מאפשרת לבחור תאריך ושעה, אך הדבר אינו מחייב זמן הגעה מדויק.",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_40732_20240925010120.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 2,
    businessTypeName: "GroceryStore",
    defaultDeliveryRuleType: "Future",
  },
  {
    restaurantId: 7306,
    restaurantName: "הפינה החלבית",
    localizationNames: {
      he: "הפינה החלבית",
      en: "Hapina Hahalavit",
    },
    restaurantAddress: "המלאכה, 8 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/7306.jpg",
    restaurantCuisineKeysList: ["pasta", "salads", "sandwichesWraps"],
    restaurantCuisineTypes: {
      pasta: "פסטה",
      salads: "סלטים",
      sandwichesWraps: "כריכים",
    },
    distanceFromUser: 2974.992809801346,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "11:00",
    closeTime: "14:50",
    deliveryTimeInMinutes: 45,
    numOfReviews: 1205,
    reviewsRankDecimal: 4.2,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 15,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 15,
    minimumPriceForOrder: 0,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 129,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_7306_20200205130022.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "None",
  },
  {
    restaurantId: 23382,
    restaurantName: "סלטי טומטוס",
    localizationNames: {
      he: "סלטי טומטוס",
      en: "Tomato Salads",
    },
    restaurantAddress: "שילה, 99 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/23382.png",
    restaurantCuisineKeysList: ["salads", "pasta", "sandwichesWraps"],
    restaurantCuisineTypes: {
      salads: "סלטים",
      pasta: "פסטה",
      sandwichesWraps: "כריכים",
    },
    distanceFromUser: 1716.7170204918443,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "10:30",
    closeTime: "22:30",
    deliveryTimeInMinutes: 45,
    numOfReviews: 920,
    reviewsRankDecimal: 4.3,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 30,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: false,
    restaurantPopularityScore: 111,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-default-card-image/CuzineType_defaultcuisine_05.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 28581,
    restaurantName: "מקדונלד'ס ראש העין לב אפק",
    localizationNames: {
      he: "מקדונלד'ס ראש העין לב אפק",
      en: "McDonald’s Rosh Ha'ain Lev Afek (kosher)",
    },
    restaurantAddress: "מבצע בזק, 1 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/28581.jpeg",
    restaurantCuisineKeysList: ["burgers"],
    restaurantCuisineTypes: {
      burgers: "המבורגר",
    },
    distanceFromUser: 1120.5432570101805,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "11:00",
    closeTime: "14:00",
    deliveryTimeInMinutes: 45,
    numOfReviews: 752,
    reviewsRankDecimal: 3.8,
    discountPercent: 0,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: false,
    restaurantPopularityScore: 284,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement:
      "המוצרים ומחיריהם במשלוחים וב-TA עשוים להיות שונים מהתפריט הנמכר במסעדות. ",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_28581_20231030132440.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "None",
  },
  {
    restaurantId: 46623,
    restaurantName: "הפריקסה של חיימיקו",
    localizationNames: {
      he: "הפריקסה של חיימיקו",
      en: "Haymiko Fricassee",
    },
    restaurantAddress: "הרב שלום שבזי, 58 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46623.jpg",
    restaurantCuisineKeysList: ["sandwichesWraps", "bakery", "homeMade"],
    restaurantCuisineTypes: {
      sandwichesWraps: "כריכים",
      bakery: "מאפים",
      homeMade: "אוכל ביתי",
    },
    distanceFromUser: 3044.7709047957496,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "09:30",
    closeTime: "22:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 2,
    reviewsRankDecimal: 4.5,
    discountPercent: 0,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 16,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 16,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        type: "New",
        value: "New",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 87,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46623_20251126100534.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 46461,
    restaurantName: "בי 12 פריים בוצ'רי",
    localizationNames: {
      he: "בי 12 פריים בוצ'רי",
      en: "B12 Prime Buchery",
    },
    restaurantAddress: "שדרות שלמה המלך, 2 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46461.jpg",
    restaurantCuisineKeysList: ["meatGrill"],
    restaurantCuisineTypes: {
      meatGrill: "בשרים",
    },
    distanceFromUser: 3432.363259482698,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "10:30",
    closeTime: "22:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 5,
    reviewsRankDecimal: 3,
    discountPercent: 0,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 16,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 16,
    minimumPriceForOrder: 50,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        type: "New",
        value: "New",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 148,
    futureOrdersAvailable: true,
    futureOrderSupported: true,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46461_20251111100451.jpg",
    isScoober: true,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 26217,
    restaurantName: "שיא סלט",
    localizationNames: {
      he: "שיא סלט",
      en: "C Salat",
    },
    restaurantAddress: "הסדנא, 4 פתח תקווה",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/26217.png",
    restaurantCuisineKeysList: ["salads", "sandwichesWraps", "homeMade"],
    restaurantCuisineTypes: {
      salads: "סלטים",
      sandwichesWraps: "כריכים",
      homeMade: "אוכל ביתי",
    },
    distanceFromUser: 11068.465104685503,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "08:00",
    closeTime: "14:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 5331,
    reviewsRankDecimal: 4.4,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 12,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 12,
    minimumPriceForOrder: 200,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 3999,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement:
      "כ-5000 לקוחות ממליצים-אינם טועים ! כשר מהדרין, טריות יום יומית = המתכון לסלט מנצח   ",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-default-card-image/CuzineType_defaultcuisine_06.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "None",
  },
  {
    restaurantId: 17419,
    restaurantName: "סושי במושבה",
    localizationNames: {
      he: "סושי במושבה",
      en: "Sushi BaMoshava",
    },
    restaurantAddress: "מוטה גור, 9 פתח תקווה",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/17419.jpg",
    restaurantCuisineKeysList: ["japaneseSushi", "asianFusion"],
    restaurantCuisineTypes: {
      japaneseSushi: "סושי",
      asianFusion: "אסייתי",
    },
    distanceFromUser: 10563.970709724706,
    isOpenNow: false,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "08:00",
    closeTime: "22:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 12055,
    reviewsRankDecimal: 4.4,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 30,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 30,
    minimumPriceForOrder: 200,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [],
    isTerminalActive: true,
    restaurantPopularityScore: 5124,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement:
      "יש טונה! מטבח המשלוחים נפתח בשעה 12:00 כל המשלוחים צפויים להגיע עד השעה 13:30 ",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_17419_1910030505.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "RestaurantIsBusy",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "None",
  },
  {
    restaurantId: 46529,
    restaurantName: "All in zone - מעל 700 מותגים ",
    localizationNames: {
      he: "All in zone - מעל 700 מותגים ",
      en: "HTZ",
    },
    restaurantAddress: "",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46529.png",
    restaurantCuisineKeysList: ["others"],
    restaurantCuisineTypes: {
      others: "שונות",
    },
    distanceFromUser: 0,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "07:00",
    closeTime: "23:45",
    deliveryTimeInMinutes: 60,
    numOfReviews: 0,
    reviewsRankDecimal: 0,
    discountPercent: 5,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 0,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 0,
    minimumPriceForOrder: 0,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        minimumPriceForDiscount: 0,
        discountType: "Percent",
        type: "DiscountCoupon",
        value: "5%",
        imageUrl: null,
        companyId: 0,
      },
      {
        type: "New",
        value: "New",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: false,
    restaurantPopularityScore: 214,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "מעל 700 מותגים בכרטיס אחד🎉🤩",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46529_20251207123239.jpeg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 5,
    businessTypeName: "VoucherCard",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 41907,
    restaurantName: "צ'ו טו",
    localizationNames: {
      he: "צ'ו טו",
      en: "Chu Tu",
    },
    restaurantAddress: "הסיבים, 18 פתח תקווה",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/41907.jpg",
    restaurantCuisineKeysList: ["asianFusion"],
    restaurantCuisineTypes: {
      asianFusion: "אסייתי",
    },
    distanceFromUser: 11297.88355885631,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "11:00",
    closeTime: "23:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 526,
    reviewsRankDecimal: 4.2,
    discountPercent: 15,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 25,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 25,
    minimumPriceForOrder: 250,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        minimumPriceForDiscount: 0,
        discountType: "Percent",
        type: "DiscountCoupon",
        value: "15%",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 1136,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "*",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_41907_20240320163150.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 46456,
    restaurantName: "איט בר",
    localizationNames: {
      he: "איט בר",
      en: "Eat Bar",
    },
    restaurantAddress: "משה דיין, 2 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46456.jpg",
    restaurantCuisineKeysList: ["burgers", "meatGrill"],
    restaurantCuisineTypes: {
      burgers: "המבורגר",
      meatGrill: "בשרים",
    },
    distanceFromUser: 1379.6003293754875,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: true,
    openTime: "11:30",
    closeTime: "22:45",
    deliveryTimeInMinutes: 60,
    numOfReviews: 1023,
    reviewsRankDecimal: 4.6,
    discountPercent: 0,
    isKosher: true,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 19,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 19,
    minimumPriceForOrder: 70,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        type: "New",
        value: "New",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 105,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46456_20251125091121.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
  {
    restaurantId: 46470,
    restaurantName: "אנסלדה",
    localizationNames: {
      he: "אנסלדה",
      en: " N Salada",
    },
    restaurantAddress: "זהרה אלפסיה, 9 ראש העין",
    restaurantLogoUrl:
      "https://d25t2285lxl5rf.cloudfront.net/images/shops/46470.png",
    restaurantCuisineKeysList: ["salads", "poke"],
    restaurantCuisineTypes: {
      salads: "סלטים",
      poke: "פוקי",
    },
    distanceFromUser: 328.62826588606583,
    isOpenNow: true,
    isActive: true,
    isDeliveryEnabled: true,
    isPickupEnabled: false,
    openTime: "11:00",
    closeTime: "23:00",
    deliveryTimeInMinutes: 60,
    numOfReviews: 1,
    reviewsRankDecimal: 5,
    discountPercent: 0,
    isKosher: false,
    isVegan: false,
    isGlutenFree: false,
    isEnvironmentFriendly: false,
    deliveryFee: 15,
    deliveryPriceBeforeCompanyDiscount: 0,
    deliveryFeeAmount: 15,
    minimumPriceForOrder: 100,
    minimumForPooledOrder: 0,
    isPooledOrderRestaurant: false,
    hasActivePoolRule: false,
    pooledOrderSum: 0,
    estimatedNumberOfOrdersInPoolOrder: 0,
    tags: [
      {
        type: "New",
        value: "New",
        imageUrl: null,
        companyId: 0,
      },
    ],
    isTerminalActive: true,
    restaurantPopularityScore: 16,
    futureOrdersAvailable: false,
    futureOrderSupported: false,
    announcement: "",
    profileImageUrl:
      "https://cdn.10bis.co.il/restaurant-card-image/ResCard_46470_20251110114525.jpg",
    isScoober: false,
    voucherRestaurant: false,
    tempClosedReason: "",
    futureOrderTodayBeginTime: null,
    isDiningRoomRes: false,
    businessType: 1,
    businessTypeName: "Restaurant",
    defaultDeliveryRuleType: "Asap",
  },
];

const Body = () => {
  return (
    <div className="body">
      <div className="search">Search</div>
      <div className="res-container">
        {resList.map((restaurant) => (
          <RestaurantCard key={restaurant.restaurantId} resData={restaurant} />
        ))}
      </div>
    </div>
  );
};

const AppLayout = () => {
  return (
    <div className="app">
      <Header />
      <Body />
    </div>
  );
};

const root = createRoot(document.getElementById("root"));

root.render(<AppLayout />);
